# Generated by Django 4.2.26 on 2026-03-25 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loteria", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeros", models.JSONField()),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monto_por_numero",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("combinaciones_generadas", models.JSONField(blank=True, null=True)),
                ("premiados", models.JSONField(blank=True, null=True)),
                (
                    "premio_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("paga", models.BooleanField(default=False)),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "loteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loteria.loteria",
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loteria.modalidad",
                    ),
                ),
                (
                    "tirada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas",
                        to="loteria.tirada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Apuesta",
                "verbose_name_plural": "Apuestas",
                "ordering": ["-fecha"],
            },
        ),
    ]
