# Generated by Django 4.2.26 on 2026-03-25 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nuevo_usuario", "Nuevo usuario registrado"),
                            ("acreditacion_pendiente", "Acreditación pendiente"),
                            ("acreditacion_aprobada", "Acreditación aprobada"),
                            ("acreditacion_rechazada", "Acreditación rechazada"),
                            ("extraccion_pendiente", "Extracción pendiente"),
                            ("extraccion_aprobada", "Extracción aprobada"),
                            ("extraccion_rechazada", "Extracción rechazada"),
                            ("apuesta_creada", "Apuesta creada"),
                            ("apuesta_ganadora", "Apuesta ganadora"),
                            ("apuesta_perdedora", "Apuesta perdedora"),
                            ("resultado_publicado", "Resultado publicado"),
                            ("saldo_ajustado", "Saldo ajustado"),
                            ("saldo_bajo", "Saldo bajo"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("datos", models.JSONField(blank=True, null=True)),
                ("leida", models.BooleanField(default=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha"],
            },
        ),
    ]
